;(2.7)
;problem related Alyssa P. Hacker
(define (make-interval a b) (cons a b))
(define (greater-one a b) (if (< a b) b a))
(define (lesser-one a b) (if (> a b) b a))
(define (upper-bound interval) (greater-one (car interval) (cdr interval)))
(define (lower-bound interval) (lesser-one (car interval) (cdr interval)))

;(2.8)
(define (add-interval x y)
  (make-interval (+ (lower-bound x) (lower-bound y))
                 (+ (upper-bound x) (upper-bound y))))
(define (sub-interval x y)
  (make-interval (- (lower-bound x) (upper-bound y))
                 (- (upper-bound x) (lower-bound y))))
(define (mul-interval x y)
  (let ((p1 (* (lower-bound x) (lower-bound y)))
        (p2 (* (lower-bound x) (upper-bound y)))
        (p3 (* (upper-bound x) (lower-bound y)))
        (p4 (* (upper-bound x) (upper-bound y))))
    (make-interval (max p1 p2 p3 p4)
                   (min p1 p2 p3 p4))))
(define (div-interval x y)
  (mul-interval x (make-interval (/ 1.0 (upper-bound y))
                                 (/ 1.0 (lower-bound y)))))

(define R1 (make-interval 2.1 4.9))
(define R2 (make-interval 0.32 1.46))
(define R3 (make-interval (- 1.12) 0.31))
